### ISSUE TITLE
Add Energy Usage to the API -> Home Assistant Energy Usage

### ISSUE THREAD

**Issue by deftdawg** [broox/python-nuheat#7]
Wondering Energy usage can be added?

I'm thinking maybe Hourly could be reported downstream to Home Assistant to make NuHeat contribute to the Energy stats for consumption devices in a similar manner to how some smart plugs report energy consumption.   

I've done the this work to update the [Neurio component](https://github.com/home-assistant/core/pull/54445), hopefully that will arrive with in HA's 2021.12.1 release.  I'd be cool to try to make this work downstream for HA's NuHeat component (though I'm not a native python dev; so might take a while to get merged). :)

- https://www.home-assistant.io/docs/energy/
- https://youtu.be/W7mVagcssZY -- Demo of HA Energy dashboards, etc

**Comment by kaijk** [comment]
I up-vote this request for the API to support hourly energy reporting.  I too use Home Assistant with a nuheat thermostat and would appreciate the energy data being available.
Thanks.

**Comment by trdischat** [comment]
Just adding my voice to this request. It certainly looks like the nuheat API supports queries for energy use.

**Comment by kut** [comment]
Looks like the GET endpoint `/api/v1/EnergyLog/Day/{serialNumber}/{date}` would return:

```

{
  "energyUsageType": "string",
  "energyUsageFrom": "string",
  "energyUsageTo": "string",
  "mondayIsFirstDay": true,
  "energyUsage": [
    {
      "entry": "string",
      "minutes": 0,
      "energyKWattHour": 0,
      "chargeKWattHour": 0
    }
  ]
}

```

See: https://api.mynuheat.com/swagger/

Do folks still think this is interesting? I also would be very interested in adding this to Home Assistant energy monitoring...

**Comment by barndawgie** [comment]
A little further investigation seems to indicate that they aren't actually metering anything - simply estimate kWh based on your indicated 1) Square Footage 2) Hours of Runtime, and 3) Watts per square foot (which they say is generally 12W).

So you can replicate this pretty easily with a Template Sensor like this:

```jinja
{% set watts_per_square_foot = 12 %}
{% set square_footage = 28 %}

{% if state_attr('climate.basement_bath','hvac_action') == 'heating'%}
  {{ watts_per_square_foot * square_footage | int }}
{% else %}
  {{ 0 | int }}
{% endif %}
```

Just replace 12 with your expected W/Area and 28 with the Area of your heated floor. That will create a Power sensor and you can then create an Integration Helper to get kWh used.

I'm going to try and validate this against the API but it seems to be having some issues currently.

**Comment by trdischat** [comment]
> Just replace 12 with your expected W/Area and 28 with the Area of your heated floor. That will create a Power sensor and you can then create an Integration Helper to get kWh used.

I have used a very similar approach for years. The cable in my floor has a rated draw of 6 amps. That times 120 volts gives me 720 watts. That times runtime (using an integration sensor) yields kWh. My template power sensor is quite similar to yours, but I added a tiny amount of random variation to the values. Otherwise, the integration sensor doesn't work correctly.
```yaml
- name: "Power Consumption NuHeat"
  unit_of_measurement: "W"
  device_class: power
  state: >-
    {% if state_attr('climate.nuheat', 'hvac_action') == 'heating' %}
      {{ 720.0  + ( ( range(-100, 101) | random ) / 10000 ) }}
    {% else %}
      {{ 0.0 }}
    {% endif %}
- platform: integration
  source: sensor.power_consumption_nuheat
  name: "Energy Consumption NuHeat"
  unit_prefix: k
  unit_time: h
  method: left
```
